name: WorldTaste
version: ${version}
main: com.haiman233.worldtaste.WorldTastePlugin
api-version: '1.21'
authors: [haiman233, wickidcow]
description: WorldTaste - a comprehensive food and culture addon for Slimefun Legacy.
depend: [Slimefun]
softdepend: [Gastronomicon, ExoticGarden, Cultivation, InfinityExpansion, InfinityExpansion2, LogiTech, JustEnoughGuide]
website: https://github.com/wickidcow/SF_WorldTaste
